--- #YAML:1.0
name:                    Text-CSV_XS
version:                 0.90
abstract:                Comma-Separated Values manipulation routines
license:                 perl
author:              
    - H.Merijn Brand <h.m.brand@xs4all.nl>
generated_by:            Author
distribution_type:       module
provides:
    Text::CSV_XS:
        file:            CSV_XS.pm
        version:         0.90
requires:     
    perl:                5.006001
    DynaLoader:          0
    IO::Handle:          0
recommends:     
    perl:                5.016000
configure_requires:
    ExtUtils::MakeMaker: 0
build_requires:
    Config:              0
test_requires:
    Test::Harness:       0
    Test::More:          0
    Tie::Scalar:         0
resources:
    license:             http://dev.perl.org/licenses/
    repository:          http://repo.or.cz/w/Text-CSV_XS.git
meta-spec:
    version:             1.4
    url:                 http://module-build.sourceforge.net/META-spec-v1.4.html
