--- 
abstract: Comma-Separated Values manipulation routines
author: 
  - H.Merijn Brand <h.m.brand@xs4all.nl>
build_requires: 
  Config: 0
configure_requires: 
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: Author, CPAN::Meta::Converter version 2.131560
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-CSV_XS
provides: 
  Text::CSV_XS: 
    file: CSV_XS.pm
    version: '1.00'
recommends: 
  Encode: '2.51'
  perl: '5.016003'
requires: 
  DynaLoader: 0
  IO::Handle: 0
  Test::More: 0
  Tie::Scalar: 0
  perl: '5.006001'
resources: 
  license: http://dev.perl.org/licenses/
  repository: http://repo.or.cz/r/Text-CSV_XS.git
version: '1.00'
